from django.urls import path

from .views import (
    TeacherAnnoncesListView,
    TeacherAnnouncementCreateView,
    TeacherAnnouncementDeleteView,
    TeacherAnnouncementUpdateView,
    TeacherCourseDetailView,
    TeacherCoursesListView,
    TeacherDashboardView,
    TeacherDocumentsView,
    TeacherEvaluationsListView,
    TeacherFichierEvaluationView,
    TeacherGradeEvaluationView,
    TeacherOuvrirDepotView,
    TeacherParametresEvaluationView,
    TeacherPrepareEvaluationsView,
    TeacherPublishGradesView,
    TeacherPublishGradeView,
    TeacherResourceDeleteView,
    TeacherResourceUpdateView,
    TeacherResourceUploadView,
)
from .views_devoirs import (
    TeacherDelaiView,
    TeacherDevoirActionView,
    TeacherDevoirCreateView,
    TeacherDevoirDetailView,
    TeacherDevoirsListView,
    TeacherDevoirUpdateView,
    TeacherEtudiantsListView,
    TeacherReviseGradeView,
)
from .views_qcm import (
    TeacherChoixCreateView,
    TeacherChoixDeleteView,
    TeacherGroupeCreateView,
    TeacherGroupeDeleteView,
    TeacherGroupeMessageView,
    TeacherGroupesListView,
    TeacherGroupeUpdateView,
    TeacherQuestionCreateView,
    TeacherQuestionDeleteView,
    TeacherQuestionDetailView,
    TeacherQuestionnaireView,
    TeacherQuestionUpdateView,
    TeacherRecorrigerView,
)

app_name = "lms"

urlpatterns = [
    path("", TeacherDashboardView.as_view(), name="dashboard"),
    # ── Devoirs ──
    path("devoirs/", TeacherDevoirsListView.as_view(), name="devoirs_list"),
    path("devoirs/nouveau/", TeacherDevoirCreateView.as_view(), name="devoir_create"),
    path("cours/<int:cours_pk>/devoir/", TeacherDevoirCreateView.as_view(), name="devoir_create_pour_cours"),
    path("devoirs/<int:pk>/", TeacherDevoirDetailView.as_view(), name="devoir_detail"),
    path("devoirs/<int:pk>/modifier/", TeacherDevoirUpdateView.as_view(), name="devoir_update"),
    path("devoirs/<int:pk>/action/", TeacherDevoirActionView.as_view(), name="devoir_action"),
    path("copies/<int:pk>/delai/", TeacherDelaiView.as_view(), name="accorder_delai"),
    # ── Recours ──
    path("evaluations/<int:pk>/reviser/", TeacherReviseGradeView.as_view(), name="revise_grade"),
    # ── Questionnaires ──
    path("questionnaires/<int:pk>/", TeacherQuestionnaireView.as_view(), name="questionnaire"),
    path("questionnaires/<int:pk>/question/", TeacherQuestionCreateView.as_view(), name="question_create"),
    path("questionnaires/<int:pk>/recorriger/", TeacherRecorrigerView.as_view(), name="questionnaire_recorriger"),
    path("questions/<int:pk>/", TeacherQuestionDetailView.as_view(), name="question_detail"),
    path("questions/<int:pk>/modifier/", TeacherQuestionUpdateView.as_view(), name="question_update"),
    path("questions/<int:pk>/supprimer/", TeacherQuestionDeleteView.as_view(), name="question_delete"),
    path("questions/<int:pk>/proposition/", TeacherChoixCreateView.as_view(), name="choix_create"),
    path("propositions/<int:pk>/supprimer/", TeacherChoixDeleteView.as_view(), name="choix_delete"),
    # ── Groupes de travail ──
    path("groupes/", TeacherGroupesListView.as_view(), name="groupes_list"),
    path("groupes/nouveau/", TeacherGroupeCreateView.as_view(), name="groupe_create"),
    path("groupes/<int:pk>/modifier/", TeacherGroupeUpdateView.as_view(), name="groupe_update"),
    path("groupes/<int:pk>/supprimer/", TeacherGroupeDeleteView.as_view(), name="groupe_delete"),
    path("groupes/<int:pk>/message/", TeacherGroupeMessageView.as_view(), name="groupe_message"),
    # ── Mes étudiants ──
    path("etudiants/", TeacherEtudiantsListView.as_view(), name="etudiants_list"),
    path("cours/", TeacherCoursesListView.as_view(), name="courses_list"),
    path("cours/<int:pk>/", TeacherCourseDetailView.as_view(), name="course_detail"),
    path("cours/<int:cours_pk>/ressource/", TeacherResourceUploadView.as_view(), name="resource_upload"),
    path("ressources/<int:pk>/modifier/", TeacherResourceUpdateView.as_view(), name="resource_update"),
    path("ressources/<int:pk>/supprimer/", TeacherResourceDeleteView.as_view(), name="resource_delete"),
    path("cours/<int:cours_pk>/annonce/", TeacherAnnouncementCreateView.as_view(), name="announcement_create"),
    path("cours/<int:pk>/publier-notes/", TeacherPublishGradesView.as_view(), name="publish_grades"),
    path("evaluations/<int:pk>/publier/", TeacherPublishGradeView.as_view(), name="publish_grade"),
    path("cours/<int:pk>/preparer-evaluations/", TeacherPrepareEvaluationsView.as_view(), name="prepare_evaluations"),
    path("evaluations/", TeacherEvaluationsListView.as_view(), name="evaluations_list"),
    path("evaluations/<int:pk>/noter/", TeacherGradeEvaluationView.as_view(), name="grade_evaluation"),
    path("documents/", TeacherDocumentsView.as_view(), name="documents"),
    path(
        "evaluations/<int:pk>/fichier/<str:genre>/",
        TeacherFichierEvaluationView.as_view(),
        name="evaluation_fichier",
    ),
    path(
        "cours/<int:pk>/evaluation/",
        TeacherParametresEvaluationView.as_view(),
        name="parametres_evaluation",
    ),
    path("cours/<int:pk>/depot/", TeacherOuvrirDepotView.as_view(), name="basculer_depot"),
    path("annonces/", TeacherAnnoncesListView.as_view(), name="annonces_list"),
    path("annonces/<int:pk>/modifier/", TeacherAnnouncementUpdateView.as_view(), name="announcement_update"),
    path("annonces/<int:pk>/supprimer/", TeacherAnnouncementDeleteView.as_view(), name="announcement_delete"),
]
