# Generated by Django 5.2.16 on 2026-07-25 19:41

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("formations", "0003_professeur_autres_engagements_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Chapitre",
                "verbose_name_plural": "Chapitres",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="InscriptionModule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("parcours", "Parcours"),
                            ("session", "Session académique"),
                            ("octroi_manuel", "Octroi manuel"),
                            ("libre", "Accès libre"),
                        ],
                        default="parcours",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("expire", "Expiré"),
                            ("termine", "Terminé"),
                            ("revoque", "Révoqué"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                (
                    "date_debut_acces",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Début d'accès",
                    ),
                ),
                (
                    "date_fin_acces",
                    models.DateField(blank=True, null=True, verbose_name="Fin d'accès"),
                ),
                (
                    "progression_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Progression (%)",
                    ),
                ),
                ("date_completion", models.DateTimeField(blank=True, null=True)),
                ("motif_revocation", models.TextField(blank=True)),
                (
                    "suspendu_par_propagation",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_modules",
                        to="academics.profiletudiant",
                    ),
                ),
                (
                    "octroye_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acces_octroyes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accès à un module",
                "verbose_name_plural": "Accès aux modules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttestationModule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                (
                    "code_verification",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "date_emission",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "fichier_pdf",
                    models.FileField(blank=True, upload_to="elearning/attestations/%Y/"),
                ),
                (
                    "inscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestation",
                        to="elearning.inscriptionmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attestation de module",
                "verbose_name_plural": "Attestations de module",
                "ordering": ["-date_emission"],
            },
        ),
        migrations.CreateModel(
            name="Lecon",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                (
                    "type_lecon",
                    models.CharField(
                        choices=[
                            ("video", "Vidéo"),
                            ("document", "Document"),
                            ("texte", "Texte"),
                            ("lien_externe", "Lien externe"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "document",
                    models.FileField(blank=True, upload_to="elearning/documents/%Y/%m/"),
                ),
                ("lien_externe", models.URLField(blank=True)),
                ("contenu_texte", models.TextField(blank=True)),
                (
                    "duree_secondes",
                    models.PositiveIntegerField(default=0, verbose_name="Durée"),
                ),
                (
                    "apercu_gratuit",
                    models.BooleanField(
                        default=False,
                        help_text="Accessible sans compte ni droit — vitrine du module",
                        verbose_name="Aperçu gratuit",
                    ),
                ),
                (
                    "obligatoire",
                    models.BooleanField(default=True, help_text="Compte dans le calcul de complétion"),
                ),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecons",
                        to="elearning.chapitre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leçon",
                "verbose_name_plural": "Leçons",
                "ordering": ["chapitre__ordre", "ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="ModuleFormation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, verbose_name="Code module"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "objectifs",
                    models.TextField(blank=True, verbose_name="Objectifs pédagogiques"),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("initiation", "Initiation"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                        ],
                        default="initiation",
                        max_length=20,
                    ),
                ),
                (
                    "image_couverture",
                    models.ImageField(blank=True, upload_to="elearning/couvertures/"),
                ),
                (
                    "duree_totale_secondes",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Durée totale"),
                ),
                (
                    "ects",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name="ECTS"),
                ),
                (
                    "politique_acces",
                    models.CharField(
                        choices=[
                            ("public", "Public — accessible à tous"),
                            ("authentifie", "Réservé aux comptes connectés"),
                            ("inscrit_parcours", "Réservé aux inscrits du parcours"),
                            ("sur_octroi", "Sur octroi individuel"),
                        ],
                        default="inscrit_parcours",
                        max_length=20,
                        verbose_name="Politique d'accès",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("relecture", "En relecture"),
                            ("publie", "Publié"),
                            ("archive", "Archivé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                (
                    "certifiant",
                    models.BooleanField(
                        default=False,
                        help_text="Délivre une attestation à la complétion",
                    ),
                ),
                (
                    "autorise_revision",
                    models.BooleanField(
                        default=True,
                        help_text="L'étudiant peut revoir le module une fois terminé",
                        verbose_name="Relecture après complétion",
                    ),
                ),
                (
                    "seuil_completion",
                    models.PositiveSmallIntegerField(
                        default=80,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Seuil de complétion (%)",
                    ),
                ),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "cours",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules_video",
                        to="formations.cours",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules_video",
                        to="formations.discipline",
                    ),
                ),
                (
                    "prerequis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ouvre_sur",
                        to="elearning.moduleformation",
                        verbose_name="Modules prérequis",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules_video",
                        to="formations.professeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module de formation",
                "verbose_name_plural": "Modules de formation",
                "ordering": ["ordre", "titre"],
            },
        ),
        migrations.AddField(
            model_name="inscriptionmodule",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscriptions",
                to="elearning.moduleformation",
            ),
        ),
        migrations.AddField(
            model_name="chapitre",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapitres",
                to="elearning.moduleformation",
            ),
        ),
        migrations.CreateModel(
            name="ProgressionLecon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position_secondes",
                    models.PositiveIntegerField(default=0, verbose_name="Reprise à"),
                ),
                (
                    "pourcentage_vu",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "temps_visionnage_cumule",
                    models.PositiveIntegerField(default=0, verbose_name="Temps réellement visionné"),
                ),
                ("termine", models.BooleanField(default=False)),
                (
                    "date_premiere_vue",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "date_derniere_vue",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_completion", models.DateTimeField(blank=True, null=True)),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressions",
                        to="elearning.inscriptionmodule",
                    ),
                ),
                (
                    "lecon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressions",
                        to="elearning.lecon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progression",
                "verbose_name_plural": "Progressions",
                "ordering": ["-date_derniere_vue"],
            },
        ),
        migrations.CreateModel(
            name="RegleAccesParcours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "obligatoire",
                    models.BooleanField(
                        default=True,
                        help_text="Octroyé automatiquement à l'inscription",
                    ),
                ),
                (
                    "duree_acces_jours",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Vide = accès sans limite de date",
                        null=True,
                        verbose_name="Durée d'accès (jours)",
                    ),
                ),
                ("ordre_recommande", models.PositiveSmallIntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles_parcours",
                        to="elearning.moduleformation",
                    ),
                ),
                (
                    "parcours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles_modules",
                        to="formations.parcours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle d'accès par parcours",
                "verbose_name_plural": "Règles d'accès par parcours",
                "ordering": ["ordre_recommande"],
            },
        ),
        migrations.AddField(
            model_name="moduleformation",
            name="parcours",
            field=models.ManyToManyField(
                blank=True,
                related_name="modules_video",
                through="elearning.RegleAccesParcours",
                to="formations.parcours",
            ),
        ),
        migrations.CreateModel(
            name="VideoAsset",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=250)),
                (
                    "cle_stockage",
                    models.CharField(max_length=500, unique=True, verbose_name="Clé de stockage"),
                ),
                ("backend_stockage", models.CharField(default="local", max_length=20)),
                (
                    "nom_origine",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Nom du fichier d'origine",
                    ),
                ),
                (
                    "duree_secondes",
                    models.PositiveIntegerField(default=0, verbose_name="Durée"),
                ),
                (
                    "taille_octets",
                    models.BigIntegerField(default=0, verbose_name="Taille"),
                ),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "poster",
                    models.ImageField(blank=True, upload_to="elearning/posters/"),
                ),
                (
                    "statut_traitement",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En préparation"),
                            ("pret", "Prêt"),
                            ("erreur", "Erreur"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Préparation",
                    ),
                ),
                ("message_erreur", models.TextField(blank=True)),
                (
                    "cle_hls",
                    models.CharField(blank=True, max_length=500, verbose_name="Manifeste HLS"),
                ),
                (
                    "transcription",
                    models.TextField(
                        blank=True,
                        help_text="Améliore l'accessibilité et le référencement",
                    ),
                ),
                (
                    "uploade_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos_deposees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vidéo",
                "verbose_name_plural": "Vidéos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SousTitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "langue",
                    models.CharField(
                        default="fr",
                        help_text="Code BCP 47, par exemple « fr »",
                        max_length=10,
                    ),
                ),
                ("libelle", models.CharField(default="Français", max_length=100)),
                (
                    "fichier_vtt",
                    models.FileField(
                        upload_to="elearning/sous-titres/",
                        verbose_name="Fichier WebVTT",
                    ),
                ),
                ("par_defaut", models.BooleanField(default=False)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_titres",
                        to="elearning.videoasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-titres",
                "verbose_name_plural": "Sous-titres",
            },
        ),
        migrations.AddField(
            model_name="lecon",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lecons",
                to="elearning.videoasset",
            ),
        ),
        migrations.CreateModel(
            name="JournalAccesVideo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resultat",
                    models.CharField(
                        choices=[
                            ("autorise", "Autorisé"),
                            ("refuse_droit", "Refusé — aucun droit"),
                            ("refuse_expire", "Refusé — accès expiré"),
                            ("refuse_quota", "Refusé — trop de lectures simultanées"),
                            ("refuse_prerequis", "Refusé — prérequis non validés"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "adresse_ip",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="Adresse IP"),
                ),
                (
                    "user_agent_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Empreinte du navigateur",
                    ),
                ),
                (
                    "ttl_accorde",
                    models.PositiveIntegerField(default=0, verbose_name="Validité accordée (s)"),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acces_video",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lecon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acces",
                        to="elearning.lecon",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acces",
                        to="elearning.videoasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accès vidéo",
                "verbose_name_plural": "Journal des accès vidéo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="inscriptionmodule",
            constraint=models.UniqueConstraint(fields=("etudiant", "module"), name="acces_unique_etudiant_module"),
        ),
        migrations.AddConstraint(
            model_name="inscriptionmodule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("date_fin_acces__isnull", True),
                    ("date_fin_acces__gte", models.F("date_debut_acces")),
                    _connector="OR",
                ),
                name="acces_fin_apres_debut",
            ),
        ),
        migrations.AddConstraint(
            model_name="inscriptionmodule",
            constraint=models.CheckConstraint(
                condition=models.Q(("progression_percent__lte", 100)),
                name="acces_progression_max_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="chapitre",
            constraint=models.UniqueConstraint(fields=("module", "ordre"), name="chapitre_ordre_unique_par_module"),
        ),
        migrations.AddConstraint(
            model_name="progressionlecon",
            constraint=models.UniqueConstraint(
                fields=("inscription", "lecon"),
                name="progression_unique_inscription_lecon",
            ),
        ),
        migrations.AddConstraint(
            model_name="progressionlecon",
            constraint=models.CheckConstraint(
                condition=models.Q(("pourcentage_vu__lte", 100)),
                name="progression_pourcentage_max_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="regleaccesparcours",
            constraint=models.UniqueConstraint(fields=("parcours", "module"), name="regle_unique_parcours_module"),
        ),
        migrations.AddConstraint(
            model_name="moduleformation",
            constraint=models.CheckConstraint(
                condition=models.Q(("seuil_completion__gte", 50), ("seuil_completion__lte", 100)),
                name="module_seuil_completion_valide",
            ),
        ),
        migrations.AddConstraint(
            model_name="soustitre",
            constraint=models.UniqueConstraint(fields=("video", "langue"), name="soustitre_langue_unique_par_video"),
        ),
        migrations.AddConstraint(
            model_name="lecon",
            constraint=models.UniqueConstraint(fields=("chapitre", "ordre"), name="lecon_ordre_unique_par_chapitre"),
        ),
        migrations.AddConstraint(
            model_name="lecon",
            constraint=models.UniqueConstraint(fields=("chapitre", "slug"), name="lecon_slug_unique_par_chapitre"),
        ),
        migrations.AddIndex(
            model_name="journalaccesvideo",
            index=models.Index(fields=["-created_at"], name="elearning_j_created_07f789_idx"),
        ),
        migrations.AddIndex(
            model_name="journalaccesvideo",
            index=models.Index(
                fields=["utilisateur", "-created_at"],
                name="elearning_j_utilisa_9d837a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalaccesvideo",
            index=models.Index(
                fields=["resultat", "-created_at"],
                name="elearning_j_resulta_fca93a_idx",
            ),
        ),
    ]
