# Generated by Django 5.2.16 on 2026-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0003_videoasset_external_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptionmodule",
            name="statut",
            field=models.CharField(
                choices=[
                    ("demande", "Demande en attente"),
                    ("actif", "Actif"),
                    ("suspendu", "Suspendu"),
                    ("expire", "Expiré"),
                    ("termine", "Terminé"),
                    ("revoque", "Révoqué"),
                ],
                default="actif",
                max_length=20,
            ),
        ),
    ]
