# Generated by Django 5.2.13 on 2026-07-27 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0004_alter_inscriptionmodule_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleformation",
            name="prix_ttc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="En euros. Sans effet si le module n'est pas vendu à l'unité.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prix TTC",
            ),
        ),
        migrations.AddField(
            model_name="moduleformation",
            name="taux_tva",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="0 si l'ITEAG est exonéré au titre de la formation professionnelle.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name="Taux de TVA (%)",
            ),
        ),
        migrations.AlterField(
            model_name="inscriptionmodule",
            name="source",
            field=models.CharField(
                choices=[
                    ("parcours", "Parcours"),
                    ("session", "Session académique"),
                    ("octroi_manuel", "Octroi manuel"),
                    ("libre", "Accès libre"),
                    ("achat", "Achat en ligne"),
                ],
                default="parcours",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="moduleformation",
            name="politique_acces",
            field=models.CharField(
                choices=[
                    ("public", "Public — accessible à tous"),
                    ("authentifie", "Réservé aux comptes connectés"),
                    ("inscrit_parcours", "Réservé aux inscrits du parcours"),
                    ("sur_octroi", "Sur octroi individuel"),
                    ("achat", "Vendu à l'unité"),
                ],
                default="inscrit_parcours",
                max_length=20,
                verbose_name="Politique d'accès",
            ),
        ),
    ]
