# Generated by Django 5.2.13 on 2026-07-28 01:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0005_moduleformation_prix_ttc_moduleformation_taux_tva_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RessourceLecon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=250)),
                ("fichier", models.FileField(blank=True, upload_to="elearning/ressources/%Y/%m/")),
                ("nom_origine", models.CharField(blank=True, max_length=250, verbose_name="Nom du fichier d'origine")),
                ("lien_externe", models.URLField(blank=True)),
                ("taille_octets", models.BigIntegerField(default=0, editable=False, verbose_name="Taille")),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "deposee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ressources_deposees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lecon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ressources", to="elearning.lecon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressource de leçon",
                "verbose_name_plural": "Ressources de leçon",
                "ordering": ["ordre", "id"],
            },
        ),
    ]
