# Generated by Django 5.2.17 on 2026-09-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_videoasset_fichier_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleformation',
            name='genre',
            field=models.CharField(choices=[('formation', 'Module de formation'), ('atelier', 'Atelier de prédication')], default='formation', help_text='Un atelier se compose comme un module, mais se présente séparément.', max_length=20, verbose_name='Nature'),
        ),
    ]
