# Generated by Django 5.2.17 on 2026-09-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0009_module_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoasset",
            name="fournisseur",
            field=models.CharField(
                choices=[
                    ("bunny", "Bunny Stream (adresse signée)"),
                    ("local", "ITEAG (adresse signée)"),
                    ("vimeo", "Vimeo (contenu public)"),
                    ("youtube", "YouTube (contenu public)"),
                ],
                default="bunny",
                max_length=20,
                verbose_name="Fournisseur de diffusion",
            ),
        ),
    ]
