# Generated by Django 5.2.16 on 2026-07-25 19:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbonneNewsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "confirme",
                    models.BooleanField(default=False, verbose_name="Confirmé"),
                ),
                ("date_confirmation", models.DateTimeField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                ("date_desinscription", models.DateTimeField(blank=True, null=True)),
                (
                    "token_confirmation",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "token_desinscription",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
            ],
            options={
                "verbose_name": "Abonné à la newsletter",
                "verbose_name_plural": "Abonnés à la newsletter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("connexion", "Connexion"),
                            ("connexion_echec", "Échec de connexion"),
                            ("deconnexion", "Déconnexion"),
                            ("creation", "Création"),
                            ("modification", "Modification"),
                            ("suppression", "Suppression"),
                            ("changement_statut", "Changement de statut"),
                            ("octroi_acces", "Octroi d'accès"),
                            ("revocation_acces", "Révocation d'accès"),
                            ("export", "Export de données"),
                            ("consultation_sensible", "Consultation sensible"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "objet_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Type d'objet"),
                ),
                (
                    "objet_id",
                    models.CharField(blank=True, max_length=64, verbose_name="Identifiant"),
                ),
                (
                    "objet_libelle",
                    models.CharField(blank=True, max_length=250, verbose_name="Libellé"),
                ),
                (
                    "adresse_ip",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="Adresse IP"),
                ),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                (
                    "metadonnees",
                    models.JSONField(blank=True, default=dict, verbose_name="Métadonnées"),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_journalisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée du journal d'audit",
                "verbose_name_plural": "Journal d'audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="core_journa_created_3c70a7_idx"),
                    models.Index(
                        fields=["utilisateur", "-created_at"],
                        name="core_journa_utilisa_6b4847_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_journa_action_542f9b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("candidature", "Candidature"),
                            ("note_publiee", "Note publiée"),
                            ("nouvelle_ressource", "Nouvelle ressource"),
                            ("nouveau_module", "Nouveau module"),
                            ("annonce", "Annonce"),
                            ("rappel_session", "Rappel de session"),
                            ("acces_octroye", "Accès octroyé"),
                            ("attestation", "Attestation disponible"),
                            ("systeme", "Information"),
                        ],
                        default="systeme",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                (
                    "url_cible",
                    models.CharField(blank=True, max_length=500, verbose_name="Lien"),
                ),
                ("lu", models.BooleanField(default=False)),
                ("date_lecture", models.DateTimeField(blank=True, null=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["destinataire", "lu", "-created_at"],
                        name="core_notifi_destina_0e66d7_idx",
                    )
                ],
            },
        ),
    ]
