# Generated by Django 5.2.16 on 2026-07-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("connexion", "Connexion"),
                    ("connexion_echec", "Échec de connexion"),
                    ("deconnexion", "Déconnexion"),
                    ("creation", "Création"),
                    ("modification", "Modification"),
                    ("suppression", "Suppression"),
                    ("changement_statut", "Changement de statut"),
                    ("demande_acces", "Demande d'accès"),
                    ("octroi_acces", "Octroi d'accès"),
                    ("revocation_acces", "Révocation d'accès"),
                    ("export", "Export de données"),
                    ("consultation_sensible", "Consultation sensible"),
                ],
                max_length=30,
            ),
        ),
    ]
