# Generated by Django 5.2.13 on 2026-08-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_journalaudit_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("candidature", "Candidature"),
                    ("note_publiee", "Note publiée"),
                    ("nouvelle_ressource", "Nouvelle ressource"),
                    ("nouveau_module", "Nouveau module"),
                    ("annonce", "Annonce"),
                    ("rappel_session", "Rappel de session"),
                    ("acces_octroye", "Accès octroyé"),
                    ("attestation", "Attestation disponible"),
                    ("securite", "Sécurité du compte"),
                    ("systeme", "Information"),
                ],
                default="systeme",
                max_length=30,
                verbose_name="Type",
            ),
        ),
    ]
