# Generated by Django 5.2.13 on 2026-07-27 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceDemandee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(max_length=150, verbose_name="Pièce demandée")),
                ("precisions", models.TextField(blank=True, verbose_name="Précisions au candidat")),
                ("obligatoire", models.BooleanField(default=True)),
                ("date_limite", models.DateField(blank=True, null=True, verbose_name="À fournir avant le")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("demandee", "Demandée"),
                            ("deposee", "Déposée — à vérifier"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée — à refournir"),
                        ],
                        default="demandee",
                        max_length=20,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(blank=True, upload_to="candidatures/pieces/%Y/%m/", verbose_name="Fichier déposé"),
                ),
                ("date_depot", models.DateTimeField(blank=True, null=True, verbose_name="Déposée le")),
                ("date_decision", models.DateTimeField(blank=True, null=True)),
                ("motif_refus", models.TextField(blank=True, verbose_name="Motif du refus")),
                (
                    "demandee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pieces_reclamees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces_demandees",
                        to="admissions.dossiercandidature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce demandée",
                "verbose_name_plural": "Pièces demandées",
                "ordering": ["statut", "-obligatoire", "libelle"],
                "constraints": [
                    models.UniqueConstraint(fields=("dossier", "libelle"), name="piece_unique_par_dossier")
                ],
            },
        ),
    ]
