# Generated by Django 5.2.13 on 2026-07-28 00:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceComplementaire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(max_length=200, verbose_name="Pièce demandée")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Ce que le candidat doit fournir exactement. Une demande vague revient deux fois.",
                        verbose_name="Précisions",
                    ),
                ),
                (
                    "obligatoire",
                    models.BooleanField(
                        default=True, help_text="Une pièce facultative n'empêche pas l'instruction du dossier."
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("demandee", "Demandée"),
                            ("deposee", "Déposée, en attente de vérification"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée, à redéposer"),
                        ],
                        default="demandee",
                        max_length=20,
                    ),
                ),
                ("fichier", models.FileField(blank=True, upload_to="candidatures/complements/%Y/%m/")),
                ("motif_refus", models.TextField(blank=True, verbose_name="Motif du refus")),
                ("date_depot", models.DateTimeField(blank=True, null=True, verbose_name="Déposée le")),
                ("date_verification", models.DateTimeField(blank=True, null=True, verbose_name="Vérifiée le")),
                (
                    "demandee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pieces_demandees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces_complementaires",
                        to="admissions.dossiercandidature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce complémentaire",
                "verbose_name_plural": "Pièces complémentaires",
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["dossier", "statut"], name="admissions__dossier_a4cbe9_idx")],
            },
        ),
    ]
