# Generated by Django 5.2.13 on 2026-07-29 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0002_piececomplementaire"),
        ("admissions", "0002_piecedemandee"),
    ]

    operations = []
