# Generated by Django 5.2.12 on 2026-04-12 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('attestation', "Attestation d'inscription"), ('releve_notes', 'Relevé de notes'), ('certificat', 'Certificat de scolarité'), ('recu', 'Reçu de paiement')], max_length=20, verbose_name='Type de document')),
                ('fichier_pdf', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='Fichier PDF')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents_administratifs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document administratif',
                'verbose_name_plural': 'Documents administratifs',
                'ordering': ['-date_generation'],
            },
        ),
    ]
