# Generated by Django 5.2.12 on 2026-08-05 00:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRedige",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "titre",
                    models.CharField(
                        help_text="Ce qui vous permet de le retrouver dans la liste. Il ne paraît pas sur le document.",
                        max_length=250,
                        verbose_name="Titre interne",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("courrier", "Courrier"),
                            ("convocation", "Convocation"),
                            ("invitation", "Invitation"),
                            ("compte_rendu", "Compte rendu"),
                            ("note_service", "Note de service"),
                            ("rapport", "Rapport"),
                            ("attestation", "Attestation"),
                            ("autre", "Autre document"),
                        ],
                        default="courrier",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Attribuée à la finalisation. Elle ne change plus ensuite.",
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "date_document",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="Date du document"),
                ),
                ("destinataire_nom", models.CharField(blank=True, max_length=200, verbose_name="Destinataire")),
                ("destinataire_adresse", models.TextField(blank=True, verbose_name="Adresse du destinataire")),
                ("objet", models.CharField(max_length=250, verbose_name="Objet")),
                ("corps", models.TextField(blank=True, verbose_name="Corps du document")),
                ("signataire_nom", models.CharField(blank=True, max_length=150, verbose_name="Signataire")),
                (
                    "signataire_qualite",
                    models.CharField(
                        blank=True,
                        help_text="Directeur, secrétaire général, responsable de la scolarité…",
                        max_length=150,
                        verbose_name="Qualité du signataire",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("finalise", "Finalisé")],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_finalisation", models.DateTimeField(blank=True, null=True, verbose_name="Finalisé le")),
                (
                    "fichier_pdf",
                    models.FileField(blank=True, upload_to="documents/rediges/%Y/%m/", verbose_name="PDF finalisé"),
                ),
                (
                    "redige_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_rediges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document rédigé",
                "verbose_name_plural": "Documents rédigés",
                "ordering": ["-date_document", "-created_at"],
                "indexes": [
                    models.Index(fields=["statut", "-date_document"], name="documents_d_statut_01fb1a_idx"),
                    models.Index(fields=["genre", "-date_document"], name="documents_d_genre_e015a5_idx"),
                ],
            },
        ),
    ]
