# Generated by Django 5.2.12 on 2026-08-05 00:52

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_documentredige"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentredige",
            name="donnees",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Champs propres au genre",
            ),
        ),
    ]
