# Generated by Django 5.2.12 on 2026-08-05 14:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_corps_en_blocs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentredige",
            name="corps",
            field=wagtail.fields.StreamField(
                [("paragraphe", 0), ("tableau", 5), ("encadre", 9), ("icone", 12), ("image", 16), ("saut_de_page", 17)],
                blank=True,
                block_lookup={
                    0: ("apps.documents.blocs.ParagrapheBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Texte"}),
                    2: ("wagtail.blocks.DecimalBlock", (), {"label": "Nombre", "required": False}),
                    3: ("wagtail.blocks.DateBlock", (), {"label": "Date", "required": False}),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    5: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("texte", 1), ("nombre", 2), ("date", 3), ("paragraphe", 4)]],
                        {"required": False},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Titre", "max_length": 140, "required": False}),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "ol", "ul", "link"], "label": "Texte"},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("information", "Information"),
                                ("avertissement", "Avertissement"),
                                ("mention_legale", "Mention légale"),
                            ],
                            "label": "Tonalité",
                        },
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("titre", 6), ("texte", 7), ("tonalite", 8)]], {}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("calendrier", "Calendrier"),
                                ("horloge", "Horloge"),
                                ("lieu", "Lieu"),
                                ("telephone", "Téléphone"),
                                ("courriel", "Courriel"),
                                ("piece_jointe", "Pièce jointe"),
                                ("attention", "Attention"),
                                ("valide", "Validé"),
                            ],
                            "label": "Pictogramme",
                        },
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {"label": "Texte", "max_length": 250}),
                    12: ("wagtail.blocks.StructBlock", [[("icone", 10), ("texte", 11)]], {}),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Image"}),
                    14: ("wagtail.blocks.CharBlock", (), {"label": "Légende", "max_length": 250, "required": False}),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("pleine", "Toute la justification"),
                                ("deux_tiers", "Deux tiers"),
                                ("moitie", "La moitié"),
                            ],
                            "label": "Largeur",
                        },
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("image", 13), ("legende", 14), ("largeur", 15)]], {}),
                    17: ("apps.documents.blocs.SautDePageBlock", (), {}),
                },
                verbose_name="Corps du document",
            ),
        ),
    ]
