# Generated by Django 5.2.13 on 2026-07-27 02:02

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("library", "0002_noticebibliographique_library_search_gin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("numero", models.CharField(editable=False, max_length=30, unique=True)),
                ("jeton_suivi", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("prenom", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("adresse", models.CharField(max_length=250)),
                ("complement_adresse", models.CharField(blank=True, max_length=250)),
                ("code_postal", models.CharField(max_length=20)),
                ("ville", models.CharField(max_length=120)),
                ("pays", models.CharField(default="Guadeloupe", max_length=100)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de confirmation"),
                            ("confirmee", "Confirmée"),
                            ("preparation", "En préparation"),
                            ("expediee", "Expédiée"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[("en_attente", "En attente"), ("confirme", "Confirmé"), ("rembourse", "Remboursé")],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[("virement", "Virement bancaire"), ("sur_place", "Paiement auprès du secrétariat")],
                        default="virement",
                        max_length=20,
                    ),
                ),
                ("total_produits", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("frais_livraison", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("transporteur", models.CharField(blank=True, max_length=120)),
                ("numero_suivi", models.CharField(blank=True, max_length=150, verbose_name="Numéro de suivi")),
                ("url_suivi_transporteur", models.URLField(blank=True, verbose_name="Lien de suivi transporteur")),
                ("stock_sorti", models.BooleanField(default=False, editable=False)),
                ("date_confirmation", models.DateTimeField(blank=True, null=True)),
                ("date_expedition", models.DateTimeField(blank=True, null=True)),
                ("date_livraison", models.DateTimeField(blank=True, null=True)),
                ("date_annulation", models.DateTimeField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes_boutique",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProduitLivre",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("sku", models.CharField(max_length=60, unique=True, verbose_name="Référence / SKU")),
                ("isbn", models.CharField(blank=True, max_length=20, verbose_name="ISBN")),
                ("auteur", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "prix_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Prix TTC",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="commerce/livres/")),
                ("poids_grammes", models.PositiveIntegerField(default=0, verbose_name="Poids (g)")),
                ("stock_physique", models.PositiveIntegerField(default=0)),
                ("stock_reserve", models.PositiveIntegerField(default=0, editable=False, verbose_name="Stock réservé")),
                ("seuil_alerte", models.PositiveIntegerField(default=2, verbose_name="Seuil d'alerte")),
                ("actif", models.BooleanField(default=True)),
                (
                    "notice",
                    models.OneToOneField(
                        blank=True,
                        help_text="Notice documentaire correspondante, lorsqu'elle existe.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produit_boutique",
                        to="library.noticebibliographique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livre en vente",
                "verbose_name_plural": "Livres en vente",
                "ordering": ["titre"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("entree", "Entrée"),
                            ("reservation", "Réservation"),
                            ("liberation", "Libération"),
                            ("sortie", "Sortie"),
                            ("ajustement", "Ajustement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("variation_physique", models.IntegerField(default=0)),
                ("variation_reserve", models.IntegerField(default=0)),
                ("stock_physique_apres", models.PositiveIntegerField()),
                ("stock_reserve_apres", models.PositiveIntegerField()),
                ("motif", models.CharField(blank=True, max_length=250)),
                (
                    "acteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_stock",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_stock",
                        to="commerce.commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements_stock",
                        to="commerce.produitlivre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=60)),
                ("titre", models.CharField(max_length=300)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantite", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("total_ligne", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lignes", to="commerce.commande"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_commandes",
                        to="commerce.produitlivre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AlerteStock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stock_disponible_detecte", models.PositiveIntegerField()),
                ("seuil", models.PositiveIntegerField()),
                ("resolue", models.BooleanField(default=False)),
                ("date_resolution", models.DateTimeField(blank=True, null=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes_stock",
                        to="commerce.produitlivre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte de stock",
                "verbose_name_plural": "Alertes de stock",
                "ordering": ["resolue", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(fields=["statut", "-created_at"], name="commerce_co_statut_31387b_idx"),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(fields=["email", "-created_at"], name="commerce_co_email_9d9657_idx"),
        ),
        migrations.AddIndex(
            model_name="produitlivre",
            index=models.Index(fields=["actif", "titre"], name="commerce_pr_actif_de6f18_idx"),
        ),
        migrations.AddIndex(
            model_name="produitlivre",
            index=models.Index(fields=["sku"], name="commerce_pr_sku_9c95e3_idx"),
        ),
        migrations.AddIndex(
            model_name="produitlivre",
            index=models.Index(fields=["isbn"], name="commerce_pr_isbn_cf7451_idx"),
        ),
        migrations.AddConstraint(
            model_name="produitlivre",
            constraint=models.CheckConstraint(
                condition=models.Q(("prix_ttc__gte", 0)), name="commerce_prix_livre_positif"
            ),
        ),
        migrations.AddConstraint(
            model_name="produitlivre",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_reserve__lte", models.F("stock_physique"))),
                name="commerce_stock_reserve_borne",
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(fields=["produit", "-created_at"], name="commerce_mo_produit_8f6a1b_idx"),
        ),
        migrations.AddConstraint(
            model_name="lignecommande",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantite__gte", 1)), name="commerce_quantite_commande_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="alertestock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resolue", False)), fields=("produit",), name="commerce_une_alerte_stock_ouverte"
            ),
        ),
    ]
