# Generated by Django 5.2.13 on 2026-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    ("carte", "Carte bancaire"),
                    ("virement", "Virement bancaire"),
                    ("sur_place", "Paiement auprès du secrétariat"),
                ],
                default="virement",
                max_length=20,
            ),
        ),
    ]
