# Generated by Django 5.2.12 on 2026-07-28 21:23

from decimal import Decimal

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0002_alter_commande_mode_paiement"),
        ("library", "0002_noticebibliographique_library_search_gin"),
    ]

    operations = [
        migrations.CreateModel(
            name="TarifLivraison",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.CharField(
                        choices=[("Guyane", "Guyane"), ("Guadeloupe", "Guadeloupe"), ("Martinique", "Martinique")],
                        max_length=20,
                    ),
                ),
                (
                    "type_livraison",
                    models.CharField(choices=[("standard", "Standard"), ("express", "Express")], max_length=20),
                ),
                (
                    "poids_max_grammes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)], verbose_name="Poids maximal (g)"
                    ),
                ),
                (
                    "prix_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Prix TTC",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tarif de livraison",
                "verbose_name_plural": "Tarifs de livraison",
                "ordering": ["destination", "type_livraison", "poids_max_grammes"],
            },
        ),
        migrations.AddField(
            model_name="commande",
            name="poids_total_grammes",
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name="Poids total (g)"),
        ),
        migrations.AddField(
            model_name="commande",
            name="type_livraison",
            field=models.CharField(
                choices=[("standard", "Standard"), ("express", "Express")], default="standard", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="pays",
            field=models.CharField(
                choices=[("Guyane", "Guyane"), ("Guadeloupe", "Guadeloupe"), ("Martinique", "Martinique")],
                default="Guadeloupe",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="produitlivre",
            name="poids_grammes",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Poids (g)"
            ),
        ),
        migrations.AddConstraint(
            model_name="produitlivre",
            constraint=models.CheckConstraint(
                condition=models.Q(("poids_grammes__gte", 1)), name="commerce_poids_livre_positif"
            ),
        ),
        migrations.AddIndex(
            model_name="tariflivraison",
            index=models.Index(
                fields=["destination", "type_livraison", "actif", "poids_max_grammes"],
                name="commerce_ta_destina_f36464_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tariflivraison",
            constraint=models.UniqueConstraint(
                fields=("destination", "type_livraison", "poids_max_grammes"), name="commerce_tarif_livraison_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="tariflivraison",
            constraint=models.CheckConstraint(
                condition=models.Q(("poids_max_grammes__gte", 1)), name="commerce_tarif_poids_positif"
            ),
        ),
        migrations.AddConstraint(
            model_name="tariflivraison",
            constraint=models.CheckConstraint(
                condition=models.Q(("prix_ttc__gt", 0)), name="commerce_tarif_prix_positif"
            ),
        ),
    ]
