# Generated by Django 5.2.12 on 2026-07-29 03:37

from datetime import date
from decimal import Decimal

from django.db import migrations, models

SOURCE_URL = (
    "https://www.laposte.fr/ecom/occ/smartedit/medias/sys_master/pdf/"
    "h4e/ha0/31034407387166/2026-04-07_Particuliers-Guadeloupe/"
    "2026-04-07-Particuliers-Guadeloupe.pdf"
)
DATE_EFFET = date(2026, 4, 1)

STANDARD_GUADELOUPE_MARTINIQUE = [
    (250, "5.49"),
    (500, "7.59"),
    (750, "9.29"),
    (1000, "9.59"),
    (2000, "11.19"),
    (5000, "17.39"),
    (10000, "25.29"),
    (15000, "31.99"),
    (30000, "39.59"),
]
STANDARD_GUYANE = [
    (500, "10.02"),
    (1000, "15.87"),
    (2000, "21.57"),
    (5000, "32.44"),
    (10000, "51.97"),
    (15000, "108.54"),
    (30000, "119.18"),
]
EXPRESS_GUADELOUPE_JUSQU_A_10_KG = [
    "18.03",
    "18.69",
    "19.53",
    "20.37",
    "21.20",
    "22.05",
    "22.83",
    "23.61",
    "24.39",
    "25.17",
    "25.95",
    "26.73",
    "27.52",
    "28.30",
    "29.08",
    "29.86",
    "30.64",
    "31.42",
    "32.20",
    "32.98",
]
EXPRESS_INTER_DOM_JUSQU_A_10_KG = [
    "30.76",
    "33.07",
    "35.22",
    "37.37",
    "39.52",
    "41.66",
    "43.35",
    "45.03",
    "46.71",
    "48.39",
    "50.07",
    "51.75",
    "53.44",
    "55.12",
    "56.80",
    "58.48",
    "60.16",
    "61.85",
    "63.53",
    "65.21",
]


def _paliers_express(prix_jusqu_a_10_kg, supplement_par_500_g):
    paliers = [(index * 500, prix) for index, prix in enumerate(prix_jusqu_a_10_kg, start=1)]
    prix_10_kg = Decimal(prix_jusqu_a_10_kg[-1])
    supplement = Decimal(supplement_par_500_g)
    for poids in range(10500, 30001, 500):
        tranches = (poids - 10000) // 500
        paliers.append((poids, str(prix_10_kg + supplement * tranches)))
    return paliers


def _charger_grille(TarifLivraison, *, destination, type_livraison, offre, transporteur, paliers):
    for poids, prix in paliers:
        valeurs = {
            "prix_ttc": Decimal(prix),
            "transporteur": transporteur,
            "offre": offre,
            "source_url": SOURCE_URL,
            "date_effet": DATE_EFFET,
            "actif": True,
        }
        tarif, cree = TarifLivraison.objects.get_or_create(
            destination=destination,
            type_livraison=type_livraison,
            poids_max_grammes=poids,
            defaults=valeurs,
        )
        if not cree and tarif.source_url == SOURCE_URL:
            for champ, valeur in valeurs.items():
                setattr(tarif, champ, valeur)
            tarif.save(update_fields=[*valeurs, "updated_at"])


def charger_tarifs_laposte_2026(apps, schema_editor):
    TarifLivraison = apps.get_model("commerce", "TarifLivraison")
    for destination in ("Guadeloupe", "Martinique"):
        _charger_grille(
            TarifLivraison,
            destination=destination,
            type_livraison="standard",
            offre="Colissimo France - livraison à domicile",
            transporteur="La Poste",
            paliers=STANDARD_GUADELOUPE_MARTINIQUE,
        )
    _charger_grille(
        TarifLivraison,
        destination="Guyane",
        type_livraison="standard",
        offre="Colissimo Outre-mer - relation de proximité",
        transporteur="La Poste",
        paliers=STANDARD_GUYANE,
    )

    _charger_grille(
        TarifLivraison,
        destination="Guadeloupe",
        type_livraison="express",
        offre="Chrono Express marchandises",
        transporteur="Chronopost",
        paliers=_paliers_express(EXPRESS_GUADELOUPE_JUSQU_A_10_KG, "0.63"),
    )
    for destination in ("Guyane", "Martinique"):
        _charger_grille(
            TarifLivraison,
            destination=destination,
            type_livraison="express",
            offre="Chrono Express marchandises",
            transporteur="Chronopost",
            paliers=_paliers_express(EXPRESS_INTER_DOM_JUSQU_A_10_KG, "1.45"),
        )


def supprimer_tarifs_laposte_2026(apps, schema_editor):
    TarifLivraison = apps.get_model("commerce", "TarifLivraison")
    TarifLivraison.objects.filter(source_url=SOURCE_URL, date_effet=DATE_EFFET).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0003_tariflivraison_commande_poids_total_grammes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariflivraison",
            name="date_effet",
            field=models.DateField(blank=True, null=True, verbose_name="Date d'effet"),
        ),
        migrations.AddField(
            model_name="tariflivraison",
            name="offre",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tariflivraison",
            name="source_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Source officielle"),
        ),
        migrations.AddField(
            model_name="tariflivraison",
            name="transporteur",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(charger_tarifs_laposte_2026, supprimer_tarifs_laposte_2026),
    ]
