# Generated by Django 5.2.13 on 2026-08-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0004_ajouter_source_et_tarifs_laposte_2026"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="motif_annulation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("demande_client", "Demande du client"),
                    ("rupture_stock", "Rupture de stock"),
                    ("paiement_non_recu", "Paiement jamais reçu"),
                    ("erreur_saisie", "Erreur de saisie ou doublon"),
                    ("adresse_invalide", "Adresse de livraison invalide"),
                    ("autre", "Autre motif"),
                ],
                max_length=30,
                verbose_name="Motif de l'annulation",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="precision_annulation",
            field=models.TextField(
                blank=True,
                help_text="Obligatoire lorsque le motif retenu est « Autre motif ».",
                verbose_name="Précision",
            ),
        ),
    ]
