# Generated by Django 5.2.12 on 2026-08-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0005_motif_annulation_commande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="type_livraison",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("express", "Express"),
                    ("retrait_sur_place", "Retrait à l'institut"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tariflivraison",
            name="type_livraison",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("express", "Express"),
                    ("retrait_sur_place", "Retrait à l'institut"),
                ],
                max_length=20,
            ),
        ),
    ]
