# Generated by Django 5.2.12 on 2026-08-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0006_retrait_sur_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="remise",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant déduit du total produits (remise étudiant, code promo…).",
                max_digits=10,
                verbose_name="Remise accordée",
            ),
        ),
    ]
