# Generated by Django 5.2.12 on 2026-04-12 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=250)),
                ('contenu', models.TextField()),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cours_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='academics.coursdesession')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_evaluation', models.CharField(choices=[('devoir', 'Devoir'), ('examen', 'Examen'), ('stage', 'Stage'), ('dissertation', "Dissertation de fin d'études"), ('vae', 'VAE')], default='devoir', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('soumis', 'Soumis'), ('en_correction', 'En correction'), ('note', 'Noté'), ('publie', 'Publié')], default='en_attente', max_length=20)),
                ('fichier_soumis', models.FileField(blank=True, upload_to='lms/devoirs/%Y/%m/', verbose_name='Fichier remis')),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('appreciation', models.TextField(blank=True, verbose_name='Appréciation')),
                ('ects_valides', models.DecimalField(decimal_places=1, default=0, help_text='0 ou 2.5', max_digits=4, verbose_name='ECTS validés')),
                ('date_notation', models.DateTimeField(blank=True, null=True)),
                ('cours_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.coursdesession')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.profiletudiant')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RessourcePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='lms/ressources/%Y/%m/')),
                ('type_fichier', models.CharField(blank=True, help_text='PDF, DOCX, PPT, etc.', max_length=50)),
                ('taille', models.PositiveIntegerField(default=0, help_text='Taille en octets')),
                ('visible_etudiants', models.BooleanField(default=True, verbose_name='Visible par les étudiants')),
                ('cours_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='academics.coursdesession')),
                ('uploade_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_uploadees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ressource pédagogique',
                'verbose_name_plural': 'Ressources pédagogiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
