# Generated by Django 5.2.13 on 2026-07-28 00:28

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0006_profiletudiant_eglise"),
        ("lms", "0003_evaluation_date_limite_reportee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enonce", models.TextField(verbose_name="Énoncé")),
                (
                    "type_question",
                    models.CharField(
                        choices=[
                            ("choix_unique", "Une seule bonne réponse"),
                            ("choix_multiple", "Plusieurs bonnes réponses"),
                        ],
                        default="choix_unique",
                        max_length=20,
                        verbose_name="Type de question",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.25"))],
                        verbose_name="Points",
                    ),
                ),
                (
                    "explication",
                    models.TextField(
                        blank=True,
                        help_text="Montrée à l'étudiant après la correction. Une réponse fausse sans explication n'apprend rien.",
                        verbose_name="Explication",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "devoir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="lms.devoir"
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="Choix",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(max_length=500, verbose_name="Proposition")),
                ("correct", models.BooleanField(default=False, verbose_name="Réponse correcte")),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="choix", to="lms.question"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposition",
                "verbose_name_plural": "Propositions",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="GroupeEtudiants",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, help_text="Sujet du projet, consigne propre au groupe…")),
                ("couleur", models.CharField(blank=True, help_text="Repère visuel, au format #RRGGBB.", max_length=7)),
                (
                    "cours_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupes",
                        to="academics.coursdesession",
                    ),
                ),
                (
                    "membres",
                    models.ManyToManyField(
                        blank=True, related_name="groupes_de_travail", to="academics.profiletudiant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Groupe d'étudiants",
                "verbose_name_plural": "Groupes d'étudiants",
                "ordering": ["nom"],
                "constraints": [
                    models.UniqueConstraint(fields=("cours_session", "nom"), name="groupe_nom_unique_par_cours")
                ],
            },
        ),
        migrations.CreateModel(
            name="ReponseEtudiant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("points_obtenus", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("choix", models.ManyToManyField(blank=True, related_name="reponses", to="lms.choix")),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reponses", to="lms.evaluation"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reponses", to="lms.question"
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse d'étudiant",
                "verbose_name_plural": "Réponses d'étudiants",
                "ordering": ["question__ordre"],
                "constraints": [
                    models.UniqueConstraint(fields=("evaluation", "question"), name="reponse_unique_par_question")
                ],
            },
        ),
    ]
