# Generated by Django 5.2.13 on 2026-07-29 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0003_evaluation_fichier_corrige"),
        ("lms", "0004_question_choix_groupeetudiants_reponseetudiant"),
    ]

    operations = []
