# Generated by Django 5.2.13 on 2026-08-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0009_proposition_enseignement"),
        ("lms", "0006_reparer_colonnes_devoir_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="devoir",
            name="etudiants",
            field=models.ManyToManyField(
                blank=True,
                related_name="devoirs_designes",
                to="academics.profiletudiant",
                verbose_name="Étudiants désignés",
            ),
        ),
        migrations.AddField(
            model_name="devoir",
            name="groupe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devoirs",
                to="lms.groupeetudiants",
                verbose_name="Groupe de travail",
            ),
        ),
        migrations.AddField(
            model_name="devoir",
            name="portee",
            field=models.CharField(
                choices=[
                    ("cours", "Tous les inscrits au cours"),
                    ("groupe", "Un groupe de travail"),
                    ("promotion", "Une promotion"),
                    ("etudiants", "Des étudiants désignés"),
                ],
                default="cours",
                max_length=20,
                verbose_name="Destinataires",
            ),
        ),
        migrations.AddField(
            model_name="devoir",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devoirs",
                to="academics.promotion",
            ),
        ),
    ]
