# Generated by Django 5.2.12 on 2026-04-12 04:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, verbose_name='Message de confirmation')),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Page de contact',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('section_texte', 3), ('hero', 7), ('cta', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('titre', 0), ('contenu', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du bouton', 'max_length': 50, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Lien du bouton', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('titre', 0), ('sous_titre', 4), ('image', 2), ('cta_texte', 5), ('cta_lien', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 10: ('wagtail.blocks.URLBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('titre', 0), ('description', 8), ('texte_bouton', 9), ('lien', 10)]], {})}, verbose_name='Contenu')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Page de contenu',
                'verbose_name_plural': 'Pages de contenu',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'Index des événements',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('questions', wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 250}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('reponse', 1)]], {})}, verbose_name='Questions / Réponses')),
            ],
            options={
                'verbose_name': 'Page FAQ',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sous_titre', models.CharField(blank=True, max_length=250, verbose_name='Sous-titre')),
                ('body', wagtail.fields.StreamField([('hero', 5), ('section_texte', 7), ('temoignages', 12), ('cta', 16), ('faq', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du bouton', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Lien du bouton', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('titre', 0), ('sous_titre', 1), ('image', 2), ('cta_texte', 3), ('cta_lien', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('titre', 0), ('contenu', 6), ('image', 2)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Rôle / Promotion', 'max_length': 100, 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('nom', 8), ('role', 9), ('texte', 10), ('photo', 2)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Témoignages'}), 13: ('wagtail.blocks.TextBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 15: ('wagtail.blocks.URLBlock', (), {}), 16: ('wagtail.blocks.StructBlock', [[('titre', 0), ('description', 13), ('texte_bouton', 14), ('lien', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 250}), 18: ('wagtail.blocks.StructBlock', [[('question', 17), ('reponse', 6)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'FAQ'})}, verbose_name='Contenu de la page')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': "Page d'accueil",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Index des actualités',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('lieu', models.CharField(blank=True, max_length=250, verbose_name='Lieu')),
                ('description', wagtail.fields.RichTextField(verbose_name='Description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='website.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Date de publication')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Résumé')),
                ('body', wagtail.fields.RichTextField(verbose_name='Contenu')),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image à la une')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
