# Generated by Django 5.2.16 on 2026-07-25 23:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("website", "0002_contactpage_destinataire"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleCataloguePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "accroche",
                    models.CharField(
                        blank=True,
                        help_text="Phrase d'accroche affichée sous le titre.",
                        max_length=250,
                    ),
                ),
                ("introduction", wagtail.fields.RichTextField(blank=True)),
                (
                    "arguments",
                    wagtail.fields.StreamField(
                        [("argument", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("titre", 0), ("contenu", 1), ("image", 2)]],
                                {},
                            ),
                        },
                        help_text="Ce qui distingue la formation à distance de l'ITEAG.",
                        verbose_name="Arguments",
                    ),
                ),
                (
                    "texte_appel",
                    models.CharField(
                        blank=True,
                        default="Déposer une candidature",
                        max_length=120,
                        verbose_name="Texte du bouton d'appel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page catalogue vidéo",
            },
            bases=("wagtailcore.page",),
        ),
    ]
