# Generated by Django 5.2.13 on 2026-07-27 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_modulecataloguepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modulecataloguepage",
            options={"verbose_name": "Page catalogue E-Learning"},
        ),
    ]
