# Generated by Django 5.2.13 on 2026-08-03 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0003_professeur_autres_engagements_and_more"),
        ("website", "0004_alter_modulecataloguepage_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=250)),
                ("sous_titre", models.CharField(blank=True, max_length=300, verbose_name="Sous-titre")),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                (
                    "chapeau",
                    models.TextField(
                        blank=True,
                        help_text="Deux ou trois phrases d'accroche, affichées dans les listes et les résultats de recherche.",
                        max_length=600,
                        verbose_name="Chapeau",
                    ),
                ),
                ("corps", models.TextField(blank=True, verbose_name="Corps de l'article")),
                (
                    "image_principale",
                    models.ImageField(blank=True, upload_to="articles/%Y/%m/", verbose_name="Image à la une"),
                ),
                ("credit_image", models.CharField(blank=True, max_length=200, verbose_name="Crédit de l'image")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("relecture", "Soumis à relecture"),
                            ("publie", "Publié"),
                            ("retire", "Retiré"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_publication", models.DateTimeField(blank=True, null=True, verbose_name="Publié le")),
                ("date_soumission", models.DateTimeField(blank=True, null=True, verbose_name="Soumis le")),
                ("motif_refus", models.TextField(blank=True, verbose_name="Motif du renvoi en brouillon")),
                (
                    "mots_cles",
                    models.CharField(
                        blank=True,
                        help_text="Séparés par des virgules. Ils servent au référencement.",
                        max_length=250,
                        verbose_name="Mots-clés",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="articles", to="formations.professeur"
                    ),
                ),
                (
                    "relu_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles_relus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de recherche",
                "verbose_name_plural": "Articles de recherche",
                "ordering": ["-date_publication", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fichier", models.ImageField(upload_to="articles/illustrations/%Y/%m/")),
                ("legende", models.CharField(blank=True, max_length=250, verbose_name="Légende")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="illustrations", to="website.article"
                    ),
                ),
            ],
            options={
                "verbose_name": "Illustration d'article",
                "verbose_name_plural": "Illustrations d'article",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["statut", "-date_publication"], name="website_art_statut_503fb0_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["auteur", "statut"], name="website_art_auteur__53de6e_idx"),
        ),
    ]
