# Generated by Django 5.2.13 on 2026-08-03 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_articles_recherche"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-date_publication", "-created_at"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
