# Generated by Django 5.2.12 on 2026-08-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_renommer_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="motif_retrait",
            field=models.TextField(blank=True, verbose_name="Motif de la demande de retrait"),
        ),
        migrations.AddField(
            model_name="article",
            name="retrait_demande_le",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Retrait demandé le"),
        ),
    ]
