# Generated by Django 5.2.13 on 2026-08-04 23:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_article_motif_retrait_article_retrait_demande_le"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("section_texte", 3),
                    ("texte", 1),
                    ("image", 8),
                    ("citation", 12),
                    ("encadre", 16),
                    ("document", 20),
                    ("hero", 24),
                    ("cta", 28),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                    1: ("apps.website.models.TexteEditorialBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    3: ("wagtail.blocks.StructBlock", [[("titre", 0), ("contenu", 1), ("image", 2)]], {}),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Légende", "max_length": 250, "required": False}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Crédit", "max_length": 160, "required": False}),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("contenu", "Largeur du texte"),
                                ("large", "Large"),
                                ("pleine", "Pleine largeur"),
                            ],
                            "label": "Largeur",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("legende", 5), ("credit", 6), ("largeur", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.TextBlock", (), {"label": "Citation"}),
                    10: ("wagtail.blocks.CharBlock", (), {"label": "Auteur", "max_length": 160, "required": False}),
                    11: ("wagtail.blocks.CharBlock", (), {"label": "Source", "max_length": 200, "required": False}),
                    12: ("wagtail.blocks.StructBlock", [[("citation", 9), ("auteur", 10), ("source", 11)]], {}),
                    13: ("wagtail.blocks.CharBlock", (), {"label": "Titre", "max_length": 140, "required": False}),
                    14: (
                        "apps.website.models.TexteEditorialBlock",
                        (),
                        {"features": ["bold", "italic", "underline", "ol", "ul", "link"]},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("information", "Information"),
                                ("important", "Important"),
                                ("conseil", "Conseil"),
                            ],
                            "label": "Présentation",
                        },
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("titre", 13), ("contenu", 14), ("tonalite", 15)]], {}),
                    17: ("wagtail.documents.blocks.DocumentChooserBlock", (), {}),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Libellé du lien", "max_length": 180, "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Description", "max_length": 280, "required": False},
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("document", 17), ("titre", 18), ("description", 19)]], {}),
                    21: ("wagtail.blocks.CharBlock", (), {"max_length": 250, "required": False}),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Texte du bouton", "max_length": 50, "required": False},
                    ),
                    23: ("wagtail.blocks.URLBlock", (), {"label": "Lien du bouton", "required": False}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("titre", 0), ("sous_titre", 21), ("image", 2), ("cta_texte", 22), ("cta_lien", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    26: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                    27: ("wagtail.blocks.URLBlock", (), {}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("titre", 0), ("description", 25), ("texte_bouton", 26), ("lien", 27)]],
                        {},
                    ),
                },
                verbose_name="Contenu",
            ),
        ),
        migrations.AlterField(
            model_name="faqpage",
            name="questions",
            field=wagtail.fields.StreamField(
                [("faq", 2)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 250}),
                    1: (
                        "apps.website.models.TexteEditorialBlock",
                        (),
                        {"features": ["bold", "italic", "underline", "ol", "ul", "link"]},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("question", 0), ("reponse", 1)]], {}),
                },
                verbose_name="Questions / Réponses",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 5),
                    ("section_texte", 7),
                    ("texte", 6),
                    ("image", 12),
                    ("citation", 16),
                    ("encadre", 20),
                    ("document", 24),
                    ("temoignages", 29),
                    ("cta", 33),
                    ("faq", 36),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 250, "required": False}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Texte du bouton", "max_length": 50, "required": False},
                    ),
                    4: ("wagtail.blocks.URLBlock", (), {"label": "Lien du bouton", "required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("titre", 0), ("sous_titre", 1), ("image", 2), ("cta_texte", 3), ("cta_lien", 4)]],
                        {},
                    ),
                    6: ("apps.website.models.TexteEditorialBlock", (), {}),
                    7: ("wagtail.blocks.StructBlock", [[("titre", 0), ("contenu", 6), ("image", 2)]], {}),
                    8: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Légende", "max_length": 250, "required": False}),
                    10: ("wagtail.blocks.CharBlock", (), {"label": "Crédit", "max_length": 160, "required": False}),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("contenu", "Largeur du texte"),
                                ("large", "Large"),
                                ("pleine", "Pleine largeur"),
                            ],
                            "label": "Largeur",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 8), ("legende", 9), ("credit", 10), ("largeur", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.TextBlock", (), {"label": "Citation"}),
                    14: ("wagtail.blocks.CharBlock", (), {"label": "Auteur", "max_length": 160, "required": False}),
                    15: ("wagtail.blocks.CharBlock", (), {"label": "Source", "max_length": 200, "required": False}),
                    16: ("wagtail.blocks.StructBlock", [[("citation", 13), ("auteur", 14), ("source", 15)]], {}),
                    17: ("wagtail.blocks.CharBlock", (), {"label": "Titre", "max_length": 140, "required": False}),
                    18: (
                        "apps.website.models.TexteEditorialBlock",
                        (),
                        {"features": ["bold", "italic", "underline", "ol", "ul", "link"]},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("information", "Information"),
                                ("important", "Important"),
                                ("conseil", "Conseil"),
                            ],
                            "label": "Présentation",
                        },
                    ),
                    20: ("wagtail.blocks.StructBlock", [[("titre", 17), ("contenu", 18), ("tonalite", 19)]], {}),
                    21: ("wagtail.documents.blocks.DocumentChooserBlock", (), {}),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Libellé du lien", "max_length": 180, "required": False},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Description", "max_length": 280, "required": False},
                    ),
                    24: ("wagtail.blocks.StructBlock", [[("document", 21), ("titre", 22), ("description", 23)]], {}),
                    25: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Rôle / Promotion", "max_length": 100, "required": False},
                    ),
                    27: ("wagtail.blocks.TextBlock", (), {}),
                    28: ("wagtail.blocks.StructBlock", [[("nom", 25), ("role", 26), ("texte", 27), ("photo", 2)]], {}),
                    29: ("wagtail.blocks.ListBlock", (28,), {"label": "Témoignages"}),
                    30: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    31: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                    32: ("wagtail.blocks.URLBlock", (), {}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("titre", 0), ("description", 30), ("texte_bouton", 31), ("lien", 32)]],
                        {},
                    ),
                    34: ("wagtail.blocks.CharBlock", (), {"max_length": 250}),
                    35: ("wagtail.blocks.StructBlock", [[("question", 34), ("reponse", 18)]], {}),
                    36: ("wagtail.blocks.ListBlock", (35,), {"label": "FAQ"}),
                },
                verbose_name="Contenu de la page",
            ),
        ),
        migrations.AlterField(
            model_name="modulecataloguepage",
            name="arguments",
            field=wagtail.fields.StreamField(
                [("argument", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                    1: ("apps.website.models.TexteEditorialBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    3: ("wagtail.blocks.StructBlock", [[("titre", 0), ("contenu", 1), ("image", 2)]], {}),
                },
                help_text="Ce qui distingue la formation à distance de l'ITEAG.",
                verbose_name="Arguments",
            ),
        ),
    ]
