# Generated by Django 5.2.17 on 2026-09-06 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_actualite_brochure"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brochure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Deux ou trois phrases : ce que le visiteur trouvera dans le document.",
                        max_length=600,
                        verbose_name="Description",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("institution", "Présentation de l'institut"),
                            ("formation", "Formation ou parcours"),
                            ("admission", "Admission et inscription"),
                            ("evenement", "Événement"),
                            ("autre", "Autre document"),
                        ],
                        db_index=True,
                        default="institution",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("fichier", models.FileField(upload_to="brochures/%Y/%m/", verbose_name="Fichier de la brochure")),
                (
                    "couverture",
                    models.ImageField(
                        blank=True, upload_to="brochures/couvertures/%Y/%m/", verbose_name="Image de couverture"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("publiee", "Publiée")],
                        db_index=True,
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_publication", models.DateTimeField(blank=True, null=True, verbose_name="Publiée le")),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Les plus petits nombres passent en premier. Laissez 0 pour un classement par date.",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                ("nombre_telechargements", models.PositiveIntegerField(default=0, verbose_name="Téléchargements")),
                (
                    "deposee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brochures_deposees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Déposée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brochure",
                "verbose_name_plural": "Brochures",
                "ordering": ["ordre", "-date_publication", "-created_at"],
                "indexes": [models.Index(fields=["statut", "ordre"], name="website_bro_statut_21f075_idx")],
            },
        ),
    ]
