# Generated by Django 5.2.13 on 2026-07-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="adresse",
            field=models.CharField(blank=True, max_length=250, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="user",
            name="code_postal",
            field=models.CharField(blank=True, max_length=20, verbose_name="Code postal"),
        ),
        migrations.AddField(
            model_name="user",
            name="complement_adresse",
            field=models.CharField(blank=True, max_length=250, verbose_name="Complément d'adresse"),
        ),
        migrations.AddField(
            model_name="user",
            name="pays",
            field=models.CharField(blank=True, default="Guadeloupe", max_length=120, verbose_name="Pays"),
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Portrait affiché dans les espaces privés et sur la fiche de scolarité.",
                upload_to="comptes/photos/%Y/",
                verbose_name="Photo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ville",
            field=models.CharField(blank=True, max_length=120, verbose_name="Ville"),
        ),
    ]
