# Generated by Django 5.2.17 on 2026-09-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_renvoi_invitation_alain_nisus"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="affichage",
            field=models.CharField(
                choices=[("confortable", "Confortable"), ("compact", "Compact")],
                default="confortable",
                max_length=12,
                verbose_name="Affichage des espaces",
            ),
        ),
    ]
