# Generated by Django 5.2.17 on 2026-09-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_preference_affichage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="volet_masque",
            field=models.BooleanField(default=False, verbose_name="Volet de navigation masqué"),
        ),
    ]
