# Generated by Django 5.2.13 on 2026-07-27 13:54

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0005_alter_paiement_mode_alter_paiement_statut"),
        ("commerce", "0002_alter_commande_mode_paiement"),
        ("elearning", "0005_moduleformation_prix_ttc_moduleformation_taux_tva_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reglement",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("module", "Module de formation"),
                            ("frais_inscription", "Frais d'inscription"),
                            ("commande", "Commande de la boutique"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(help_text="Adresse à laquelle le reçu Stripe est envoyé.", max_length=254)),
                (
                    "libelle",
                    models.CharField(help_text="Ce que le payeur lit sur sa page de paiement.", max_length=250),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Montant TTC",
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Taux de TVA (%)",
                    ),
                ),
                (
                    "montant_ht",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Montant HT"),
                ),
                (
                    "montant_tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Dont TVA"),
                ),
                ("devise", models.CharField(default="EUR", max_length=3)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de paiement"),
                            ("paye", "Payé"),
                            ("echoue", "Échoué"),
                            ("abandonne", "Abandonné"),
                            ("rembourse", "Remboursé"),
                            ("litige", "Contesté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "session_stripe",
                    models.CharField(blank=True, db_index=True, max_length=255, verbose_name="Session Stripe"),
                ),
                ("intention_stripe", models.CharField(blank=True, max_length=255, verbose_name="PaymentIntent Stripe")),
                ("date_paiement", models.DateTimeField(blank=True, null=True)),
                ("date_remboursement", models.DateTimeField(blank=True, null=True)),
                ("motif_echec", models.TextField(blank=True)),
                ("contrepartie_delivree", models.BooleanField(default=False, editable=False)),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglements",
                        to="commerce.commande",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dossier crédité — obligatoire pour un module ou des frais d'inscription.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglements",
                        to="academics.profiletudiant",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglements",
                        to="elearning.moduleformation",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reglements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Règlement",
                "verbose_name_plural": "Règlements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvenementStripe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifiant", models.CharField(max_length=255, unique=True, verbose_name="Identifiant Stripe")),
                ("type_evenement", models.CharField(max_length=100, verbose_name="Type")),
                ("charge_utile", models.JSONField(default=dict, verbose_name="Contenu reçu")),
                ("traite", models.BooleanField(default=False)),
                ("erreur", models.TextField(blank=True)),
                (
                    "reglement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements",
                        to="paiements.reglement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement Stripe",
                "verbose_name_plural": "Événements Stripe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reglement",
            index=models.Index(fields=["statut", "-created_at"], name="paiements_r_statut_3d85a9_idx"),
        ),
        migrations.AddIndex(
            model_name="reglement",
            index=models.Index(fields=["nature", "-created_at"], name="paiements_r_nature_f83a12_idx"),
        ),
        migrations.AddConstraint(
            model_name="reglement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_stripe", ""), _negated=True),
                fields=("session_stripe",),
                name="paiements_session_stripe_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="reglement",
            constraint=models.CheckConstraint(
                condition=models.Q(("montant_ttc__gt", 0)), name="paiements_montant_positif"
            ),
        ),
        migrations.AddConstraint(
            model_name="reglement",
            constraint=models.CheckConstraint(
                condition=models.Q(("taux_tva__gte", 0), ("taux_tva__lte", 100)), name="paiements_taux_tva_valide"
            ),
        ),
        migrations.AddConstraint(
            model_name="reglement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("commande__isnull", True), ("module__isnull", False), ("nature", "module")),
                    models.Q(("commande__isnull", True), ("module__isnull", True), ("nature", "frais_inscription")),
                    models.Q(("commande__isnull", False), ("module__isnull", True), ("nature", "commande")),
                    _connector="OR",
                ),
                name="paiements_contrepartie_coherente",
            ),
        ),
        migrations.AddIndex(
            model_name="evenementstripe",
            index=models.Index(fields=["type_evenement", "-created_at"], name="paiements_e_type_ev_bb40d3_idx"),
        ),
    ]
