# Generated by Django 5.2.12 on 2026-04-12 04:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('type_parcours', models.CharField(choices=[('diplomant_iteag', 'Parcours diplômant ITEAG'), ('bachelor_flte', 'Parcours Bachelor FLTE'), ('libre', 'Parcours libre'), ('pro', 'ITEAG Pro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('conditions_entree', models.TextField(blank=True, verbose_name="Conditions d'entrée")),
                ('ects_requis', models.PositiveSmallIntegerField(default=180, verbose_name='ECTS requis')),
                ('duree_annees', models.PositiveSmallIntegerField(default=6, verbose_name='Durée (années)')),
                ('actif', models.BooleanField(default=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ects', models.DecimalField(decimal_places=1, default=2.5, max_digits=4, verbose_name='ECTS')),
                ('actif', models.BooleanField(default=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='formations.discipline', verbose_name='Discipline')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['discipline', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('biographie', models.TextField(blank=True)),
                ('specialite', models.CharField(blank=True, max_length=200, verbose_name='Spécialité')),
                ('photo', models.ImageField(blank=True, upload_to='professeurs/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('disciplines', models.ManyToManyField(blank=True, related_name='professeurs', to='formations.discipline')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_professeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formule', models.CharField(choices=[('toutes', 'Souscription à toutes les sessions'), ('choix', 'Souscription session au choix')], max_length=20)),
                ('type_membre', models.CharField(choices=[('fondatrice', "Membre d'église fondatrice"), ('autre', 'Autre')], max_length=20)),
                ('montant_session', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant par session (€)')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'unique_together': {('formule', 'type_membre')},
            },
        ),
    ]
