# Generated by Django 5.2.12 on 2026-04-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code cours'),
        ),
        migrations.AddField(
            model_name='cours',
            name='objectifs',
            field=models.TextField(blank=True, verbose_name='Objectifs pédagogiques'),
        ),
        migrations.AddField(
            model_name='cours',
            name='parcours',
            field=models.ManyToManyField(blank=True, related_name='cours', to='formations.parcours'),
        ),
    ]
