# Generated by Django 5.2.12 on 2026-08-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0003_professeur_autres_engagements_and_more"),
        ("library", "0002_noticebibliographique_library_search_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="bibliographie",
            field=models.ManyToManyField(
                blank=True,
                related_name="cours_recommandant",
                to="library.noticebibliographique",
                verbose_name="Bibliographie recommandée",
            ),
        ),
    ]
