# Generated by Django 5.2.12 on 2026-04-12 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0002_cours_code_cours_objectifs_cours_parcours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('annee_debut', models.PositiveSmallIntegerField(verbose_name='Année de début')),
                ('annee_fin', models.PositiveSmallIntegerField(verbose_name='Année de fin')),
                ('actif', models.BooleanField(default=True)),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='formations.parcours')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-annee_debut'],
            },
        ),
        migrations.CreateModel(
            name='ProfilEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_etudiant', models.CharField(max_length=20, unique=True, verbose_name='Numéro étudiant')),
                ('statut_inscription', models.CharField(choices=[('pre_inscrit', 'Pré-inscrit'), ('paiement_attente', 'Paiement en attente'), ('inscrit', 'Inscrit'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('inactif', 'Inactif'), ('diplome', 'Diplômé')], default='pre_inscrit', max_length=20)),
                ('eglise_fondatrice', models.BooleanField(default=False, verbose_name="Membre d'une église fondatrice")),
                ('formule_tarif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.tarif')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='formations.parcours')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_etudiant', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='academics.promotion')),
            ],
            options={
                'verbose_name': 'Profil étudiant',
                'verbose_name_plural': 'Profils étudiants',
            },
        ),
        migrations.CreateModel(
            name='SessionAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120)),
                ('periode', models.CharField(choices=[('carnaval', 'Carnaval'), ('paques', 'Pâques'), ('juillet', 'Grandes vacances'), ('toussaint', 'Toussaint')], max_length=20)),
                ('annee_academique', models.CharField(help_text='Ex: 2025-2026', max_length=9)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='planifiee', max_length=20)),
            ],
            options={
                'verbose_name': 'Session académique',
                'verbose_name_plural': 'Sessions académiques',
                'ordering': ['-date_debut'],
                'unique_together': {('periode', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_paiement', models.DateField()),
                ('mode', models.CharField(choices=[('virement', 'Virement'), ('especes', 'Espèces'), ('cheque', 'Chèque'), ('autre', 'Autre')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('recu_pdf', models.FileField(blank=True, upload_to='paiements/recus/', verbose_name='Reçu PDF')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='academics.profiletudiant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.sessionacademique')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='CreditECTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ects_obtenus', models.DecimalField(decimal_places=1, default=2.5, max_digits=4)),
                ('source', models.CharField(choices=[('iteag', 'ITEAG'), ('flte', 'FLTE')], default='iteag', max_length=10)),
                ('date_validation', models.DateField()),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='formations.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_ects', to='academics.profiletudiant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.sessionacademique')),
            ],
            options={
                'verbose_name': 'Crédit ECTS',
                'verbose_name_plural': 'Crédits ECTS',
                'ordering': ['-date_validation'],
            },
        ),
        migrations.CreateModel(
            name='CoursDeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salle', models.CharField(blank=True, max_length=100)),
                ('horaires', models.TextField(blank=True, verbose_name='Horaires indicatifs')),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('en_cours', 'En cours'), ('evaluation', 'Évaluation'), ('termine', 'Terminé')], default='programme', max_length=20)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='formations.cours')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours_de_session', to='formations.professeur')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_de_session', to='academics.sessionacademique')),
            ],
            options={
                'verbose_name': 'Cours de session',
                'verbose_name_plural': 'Cours de session',
                'unique_together': {('session', 'cours')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_stage', models.CharField(max_length=200, verbose_name='Type de stage')),
                ('lieu', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('ects', models.DecimalField(decimal_places=1, default=30, max_digits=4)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('non_valide', 'Non validé')], default='en_cours', max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='academics.profiletudiant')),
                ('tuteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_tutores', to='formations.professeur')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='VAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description_experience', models.TextField(verbose_name="Description de l'expérience")),
                ('ects_demandes', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='ECTS demandés')),
                ('ects_accordes', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='ECTS accordés')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_examen', 'En examen'), ('accorde', 'Accordé'), ('refuse', 'Refusé')], default='soumis', max_length=20)),
                ('date_soumission', models.DateField(auto_now_add=True)),
                ('date_decision', models.DateField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaes', to='academics.profiletudiant')),
            ],
            options={
                'verbose_name': 'VAE',
                'verbose_name_plural': 'VAE',
            },
        ),
        migrations.CreateModel(
            name='InscriptionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cours_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academics.coursdesession')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academics.profiletudiant')),
            ],
            options={
                'verbose_name': 'Inscription session',
                'verbose_name_plural': 'Inscriptions session',
                'unique_together': {('etudiant', 'cours_session')},
            },
        ),
    ]
