# Generated by Django 5.2.12 on 2026-07-26 02:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
        ("formations", "0003_professeur_autres_engagements_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeInscriptionCours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("soumise", "Soumise"),
                            ("paiement_attente", "Paiement à régulariser"),
                            ("confirmee", "Inscription confirmée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée par l'étudiant"),
                        ],
                        default="soumise",
                        max_length=25,
                    ),
                ),
                (
                    "montant_du",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Montant dû"),
                ),
                ("note_etudiant", models.TextField(blank=True, verbose_name="Message de l'étudiant")),
                (
                    "reference_paiement",
                    models.CharField(blank=True, max_length=120, verbose_name="Référence communiquée"),
                ),
                (
                    "justificatif_paiement",
                    models.FileField(
                        blank=True, upload_to="paiements/justificatifs/%Y/%m/", verbose_name="Justificatif communiqué"
                    ),
                ),
                ("exonere_paiement", models.BooleanField(default=False, verbose_name="Exonération de paiement")),
                ("date_decision", models.DateTimeField(blank=True, null=True)),
                ("motif_decision", models.TextField(blank=True, verbose_name="Décision / commentaire interne")),
            ],
            options={
                "verbose_name": "Demande d'inscription à un cours",
                "verbose_name_plural": "Demandes d'inscription aux cours",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueDemandeInscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ancien_statut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soumise", "Soumise"),
                            ("paiement_attente", "Paiement à régulariser"),
                            ("confirmee", "Inscription confirmée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée par l'étudiant"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "nouveau_statut",
                    models.CharField(
                        choices=[
                            ("soumise", "Soumise"),
                            ("paiement_attente", "Paiement à régulariser"),
                            ("confirmee", "Inscription confirmée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée par l'étudiant"),
                        ],
                        max_length=25,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Historique d'une demande d'inscription",
                "verbose_name_plural": "Historique des demandes d'inscription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="coursdesession",
            options={
                "ordering": ["session__date_debut", "cours__titre"],
                "verbose_name": "Cours de session",
                "verbose_name_plural": "Cours de session",
            },
        ),
        migrations.AddField(
            model_name="coursdesession",
            name="capacite",
            field=models.PositiveSmallIntegerField(default=30, verbose_name="Capacité"),
        ),
        migrations.AddField(
            model_name="coursdesession",
            name="date_limite_inscription",
            field=models.DateField(blank=True, null=True, verbose_name="Date limite d'inscription"),
        ),
        migrations.AddField(
            model_name="coursdesession",
            name="frais_inscription",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Vide : appliquer le tarif de l'étudiant. Zéro : cours gratuit.",
                max_digits=8,
                null=True,
                verbose_name="Frais spécifiques",
            ),
        ),
        migrations.AddField(
            model_name="coursdesession",
            name="informations_pratiques",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="coursdesession",
            name="inscriptions_ouvertes",
            field=models.BooleanField(default=True, verbose_name="Inscriptions ouvertes"),
        ),
        migrations.AddField(
            model_name="coursdesession",
            name="modalite",
            field=models.CharField(
                choices=[("presentiel", "Présentiel"), ("distanciel", "À distance"), ("hybride", "Hybride")],
                default="presentiel",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="coursdesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacite__gt", 0)), name="cours_session_capacite_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursdesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("frais_inscription__isnull", True), ("frais_inscription__gte", 0), _connector="OR"),
                name="cours_session_frais_positifs",
            ),
        ),
        migrations.AddField(
            model_name="demandeinscriptioncours",
            name="cours_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demandes_inscription",
                to="academics.coursdesession",
            ),
        ),
        migrations.AddField(
            model_name="demandeinscriptioncours",
            name="etudiant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demandes_inscription",
                to="academics.profiletudiant",
            ),
        ),
        migrations.AddField(
            model_name="demandeinscriptioncours",
            name="paiement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_inscription",
                to="academics.paiement",
            ),
        ),
        migrations.AddField(
            model_name="demandeinscriptioncours",
            name="traitee_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_inscription_traitees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inscriptionsession",
            name="demande",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inscription",
                to="academics.demandeinscriptioncours",
            ),
        ),
        migrations.AddField(
            model_name="historiquedemandeinscription",
            name="demande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historique",
                to="academics.demandeinscriptioncours",
            ),
        ),
        migrations.AddField(
            model_name="historiquedemandeinscription",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="demandeinscriptioncours",
            index=models.Index(fields=["statut", "-created_at"], name="academics_d_statut_33c05c_idx"),
        ),
        migrations.AddIndex(
            model_name="demandeinscriptioncours",
            index=models.Index(fields=["etudiant", "-created_at"], name="academics_d_etudian_d22d0c_idx"),
        ),
        migrations.AddConstraint(
            model_name="demandeinscriptioncours",
            constraint=models.UniqueConstraint(
                fields=("etudiant", "cours_session"), name="demande_unique_etudiant_cours_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="demandeinscriptioncours",
            constraint=models.CheckConstraint(
                condition=models.Q(("montant_du__gte", 0)), name="demande_montant_du_positif"
            ),
        ),
    ]
