# Generated by Django 5.2.16 on 2026-07-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "academics",
            "0002_demandeinscriptioncours_historiquedemandeinscription_and_more",
        ),
        ("formations", "0003_professeur_autres_engagements_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="creditects",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cours__isnull", False), ("session__isnull", False)),
                fields=("etudiant", "cours", "session", "source"),
                name="credit_ects_unique_par_cours_et_session",
            ),
        ),
    ]
