# Generated by Django 5.2.16 on 2026-07-26 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_creditects_credit_ects_unique_par_cours_et_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditects",
            name="stage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit",
                to="academics.stage",
            ),
        ),
        migrations.AddField(
            model_name="creditects",
            name="vae",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit",
                to="academics.vae",
            ),
        ),
    ]
