# Generated by Django 5.2.13 on 2026-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_creditects_stage_creditects_vae"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="mode",
            field=models.CharField(
                choices=[
                    ("virement", "Virement"),
                    ("especes", "Espèces"),
                    ("cheque", "Chèque"),
                    ("carte", "Carte bancaire"),
                    ("autre", "Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="statut",
            field=models.CharField(
                choices=[("en_attente", "En attente"), ("confirme", "Confirmé"), ("rembourse", "Remboursé")],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
