# Generated by Django 5.2.13 on 2026-07-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0005_alter_paiement_mode_alter_paiement_statut"),
        ("formations", "0003_professeur_autres_engagements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursdesession",
            name="date_examen",
            field=models.DateTimeField(
                blank=True,
                help_text="Annoncée aux étudiants sur la page du cours.",
                null=True,
                verbose_name="Date de l'examen",
            ),
        ),
        migrations.AddField(
            model_name="coursdesession",
            name="depot_fermeture",
            field=models.DateTimeField(
                blank=True,
                help_text="Après cette date, la remise est close. Vide = pas d'échéance.",
                null=True,
                verbose_name="Fermeture du dépôt",
            ),
        ),
        migrations.AddField(
            model_name="coursdesession",
            name="depot_ouverture",
            field=models.DateTimeField(
                blank=True,
                help_text="Avant cette date, aucun devoir ne peut être remis. Vide = ouvert dès maintenant.",
                null=True,
                verbose_name="Ouverture du dépôt",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursdesession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("depot_ouverture__isnull", True),
                    ("depot_fermeture__isnull", True),
                    ("depot_fermeture__gte", models.F("depot_ouverture")),
                    _connector="OR",
                ),
                name="cours_session_fenetre_depot_coherente",
            ),
        ),
    ]
