# Generated by Django 5.2.13 on 2026-07-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0005_alter_paiement_mode_alter_paiement_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiletudiant",
            name="eglise",
            field=models.CharField(blank=True, max_length=200, verbose_name="Église d'appartenance"),
        ),
    ]
