# Generated by Django 5.2.13 on 2026-07-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_coursdesession_date_examen_and_more'),
        ('academics', '0006_profiletudiant_eglise'),
    ]

    operations = [
    ]
