# Generated by Django 5.2.13 on 2026-08-02 03:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0008_numero_etudiant_sans_tiret"),
        ("formations", "0003_professeur_autres_engagements_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropositionEnseignement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("proposee", "Proposée"), ("acceptee", "Acceptée"), ("declinee", "Déclinée")],
                        default="proposee",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Mot de l'administration")),
                ("motif_refus", models.TextField(blank=True, verbose_name="Motif du refus")),
                ("date_reponse", models.DateTimeField(blank=True, null=True, verbose_name="Répondu le")),
                (
                    "cours_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propositions",
                        to="academics.coursdesession",
                        verbose_name="Cours de session",
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propositions_enseignement",
                        to="formations.professeur",
                    ),
                ),
                (
                    "proposee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propositions_envoyees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposition d'enseignement",
                "verbose_name_plural": "Propositions d'enseignement",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["professeur", "statut"], name="academics_p_profess_65aa24_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("statut", "proposee")),
                        fields=("cours_session", "professeur"),
                        name="une_seule_proposition_en_cours",
                    )
                ],
            },
        ),
    ]
