# Generated by Django 5.2.17 on 2026-09-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_profil_rattachement_facultatif'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursdesession',
            name='delai_correction_jours',
            field=models.PositiveSmallIntegerField(default=15, help_text='Au-delà, la copie remise est signalée au secrétariat. Zéro : aucun suivi.', verbose_name='Délai de correction (jours)'),
        ),
    ]
